#!/usr/bin/env bash
#
# Just install ansible so we can use that for everything else :^)

set -exuo pipefail

source "$(dirname "$0")/src/bash/setup-dotfiles-env"

if ! test -d "$DOTFILES_VENV"; then
    "$DOTFILES_BOOTSTRAP_PYTHON" -m venv "$DOTFILES_VENV"
fi

source "$DOTFILES_VENV/bin/activate"
pip install --upgrade pip setuptools wheel
pip install "ansible$DOTFILES_ANSIBLE_VERSION_SPEC"

"$DOTFILES_DIR/bin/dot-sync" "$@"
