#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

# move dotfiles to $INSTALL_BASE (default $HOME)
INSTALL_BASE="${DOTFILES_INSTALL_BASE:-$HOME}"
echo "INSTALLING TO $INSTALL_BASE" >&2

__backup_and_link() {
    src="$1"
    tar="$2"
    if [ -e "$tar" ]; then
        src_hash=$(git hash-object "$src")
        tar_hash=$(git hash-object "$tar")
        if [[ "$src_hash" != "$tar_hash" ]]; then
            ./bin/bak "$tar"
        fi
    fi
    ln -sf "$src" "$tar"
    echo "linked: $tar@ -> $src"
}

__install_dependency() {
    if uname -a | grep Ubuntu; then
        sudo apt-get install -y "$1"
    else
        echo "Unrecognized OS! Aborting..." >&2
        exit 1
    fi
}

# ensure we have `git`
which git &>/dev/null || __install_dependency git

for rcfile in ./home/*; do
    basename="$(basename "$rcfile")"
    __backup_and_link "$(pwd)/home/$basename" "$INSTALL_BASE/.$basename"
done

# set up directory structure
git_username="$( (git config --get user.email || true) | sed 's/@.*//g')"
if [ ! -z "$git_username" ]; then
    mkdir -p "$INSTALL_BASE/src/$git_username"
fi
mkdir -p "$INSTALL_BASE/.local/bin"
mkdir -p "$INSTALL_BASE/.vim/bundle/vim-airline/autoload/airline/themes"

# install vim plugins via vundle
if [ ! -d "$INSTALL_BASE/.vim/bundle/Vundle.vim" ]; then
    git clone https://github.com/VundleVim/Vundle.vim "$INSTALL_BASE/.vim/bundle/Vundle.vim"
fi
vim +PluginInstall +qall

# copy custom vim plugin into expected location :^)
ln -sf \
    "$(pwd)/vim/custom-airline-theme.vim" \
    "$INSTALL_BASE/.vim/bundle/vim-airline/autoload/airline/themes/custom.vim"

cat <<EOM
> Success! Don't forget to source $INSTALL_BASE/.bashrc :^)
EOM
