#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

# move dotfiles to $HOME

__backup_and_link() {
    src="$1"
    tar="$2"
    if [ -e "$tar" ]; then
        src_hash=$(git hash-object "$src")
        tar_hash=$(git hash-object "$tar")
        if [[ "$src_hash" != "$tar_hash" ]]; then
            ./bin/bak "$tar"
        fi
    fi
    ln -sf "$src" "$tar"
    echo "linked: $tar@ -> $src"
}

__install_dependency() {
    if uname -a | grep Ubuntu; then
        sudo apt-get install -y "$1"
    else
        echo "Unrecognized OS! Aborting..." >&2
        exit 1
    fi
}

# ensure we have `git`
which git &>/dev/null || __install_dependency git

for rcfile in ./home/*; do
    basename="$(basename "$rcfile")"
    __backup_and_link "$(pwd)/home/$basename" "$HOME/.$basename"
done

# set up directory structure
git_username="$( (git config --get user.email || true) | sed 's/@.*//g')"
[[ -z "$git_username" ]] || mkdir -p \
        "$HOME/src/$git_username" \
        "$HOME/.local/bin"

# install vim plugins via vundle
[[ -d ~/.vim/bundle/Vundle.vim ]] \
    || git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# copy custom vim plugin into expected location :^)
ln -sf \
    "$(pwd)/vim/custom-airline-theme.vim" \
    "$HOME/.vim/bundle/vim-airline/autoload/airline/themes/custom.vim"

cat <<EOM
> Success! Don't forget to source ~/.bashrc :^)
EOM
