#!/bin/sh -e

ROOT_SRC="./mnt"
ROOT_TAR="/"

USER_SRC="./home"
USER_TAR="$HOME"

usage() {
    echo "usage:

  $ ./install [-h] [-r \$ROOT_SRC] [-R \$ROOT_TAR] [-u \$USER_SRC] [-U \$USER_TAR]

        -h              show this screen and exit
        -r \$ROOT_SRC    directory to search to find files that should be
                installed in the filesystem root (default: ./mnt)
        -R \$ROOT_TAR    directory to install filesystem root riles
                (default: /)
        -u \$USER_SRC    directory to search to find files that should be
                installed in user home directories (default: ./home)
        -U \$USER_TAR    directory to install user-specific files
                (default: $HOME)
                "
    exit 1
}

while getopts ":hr:R:u:U:" opt; do
    case ${opt} in
        h)
            usage
            ;;
        r)
            ROOT_SRC="$OPTARG"
            ;;
        R)
            ROOT_TAR="$OPTARG"
            ;;
        u)
            USER_SRC="$OPTARG"
            ;;
        U)
            USER_TAR="$OPTARG"
            ;;
        ?)
            echo "install.sh: invalid option" >&2
            usage
            ;;
    esac
done

confirm="$ROOT_SRC/usr/local/bin/confirm"

echo "
install.sh config:

  system:  $ROOT_SRC => $ROOT_TAR
  user:    $USER_SRC => $USER_TAR
" >&2

if ! confirm "confirm install locations? [yN] "; then
    echo "quitting"
    exit 2
fi

INSTALL() {
    for file in $(find "$1" -type f | sed "s%$1/%%g"); do
        if [ -f "$2/$file" ]; then
            if ! confirm "overwrite $2/$file ? [yN] "; then
                echo "  not overwriting"
                break
            fi
        fi

        mkdir -p $(dirname "$2/$file")
        echo "  mv $1/$file $2/$file"
        cp "$1/$file" "$2/$file"
    done
}

INSTALL "$ROOT_SRC" "$ROOT_TAR"

# more vim setup
mkdir -p "$ROOT_TAR/etc"
echo "\" source system-wide vimrc
source $ROOT_TAR/usr/local/etc/vimrc" \
    | tee -a "$ROOT_TAR/etc/vimrc" > /dev/null


INSTALL "$USER_SRC" "$USER_TAR"

echo done
exit 0
