#!/bin/bash
cat <<BEANS
 _______________
< what's beadly >
 ---------------
        \\   ^__^
         \\  (oo)\\_______
            (__)\\       )\\/\\
                ||----w |
                ||     ||
BEANS

source $HOME/.bashrc
