#!/bin/bash

if [[ "$SH_ENV" != vim ]]; then
    cat <<BEANS
 _______________
< what's beadly >
 ---------------
        \\   ^__^
         \\  (oo)\\_______
            (__)\\       )\\/\\
                ||----w |
                ||     ||
BEANS
fi

source $HOME/.bashrc
