
" [general]
set nocompatible
filetype off

" vi can only have one version of python loaded at a time, so
" the first version that gets loaded is the only one that we
" can load.  Thus, we explicitly load python3 here...
if has('python3')
endif

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

    Plugin 'VundleVim/Vundle.vim'
    Plugin 'cakebaker/scss-syntax.vim'
    Plugin 'leafgarland/typescript-vim'
    setlocal indentkeys+=0.
    Plugin 'alvan/vim-closetag'
    Plugin 'swig'
    Plugin 'neovimhaskell/haskell-vim'
    Plugin 'hashivim/vim-terraform'
    Plugin 'hashivim/vim-packer'
    Plugin 'pearofducks/ansible-vim'
    Plugin 'rhysd/vim-clang-format'
    Plugin 'xavierd/clang_complete'
    Plugin 'scrooloose/nerdtree'
    "Plugin 'vim-syntastic/syntastic'
    Plugin 'vim-airline/vim-airline'
    Plugin 'tpope/vim-fugitive'
    Plugin 'kien/ctrlp.vim'
    Plugin 'cespare/vim-toml'
    Plugin 'psf/black'
    Plugin 'elzr/vim-json'
    Plugin 'vim-latex/vim-latex'

call vundle#end()

filetype plugin on
filetype indent on

syntax enable " highlighting

let mapleader = "\\" " for extra key combos

set history=420
set autoread " read when a file is changed from outside

set path+=**
set wildmenu
set wildmode=longest:full,full
set wildignore=*.o,*~,*.pyc,*/.git/*

set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set ignorecase " when searching
set smartcase
set incsearch " behave like modern browsers
set hlsearch " highlight search results

" display <tab> as >\u00b7+ and &nbsp; as \u23b5 (<C-v>u....)
set list
set listchars=tab:>·,nbsp:⎵
highlight SpecialKey ctermfg=darkgrey

set linebreak " softwrap: break intelligently
set showcmd " show current command buffer
set nojoinspaces
set mouse+=a " allow clicking!

set scrolloff=3 " show lines above & below cursor if possible

set lazyredraw " macro performance
set magic " regex

set showmatch " show matching brackets
set matchtime=2 " blink speed for bracket matching

set number
set relativenumber
set numberwidth=4
highlight LineNr ctermfg=DarkGrey ctermbg=NONE
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter * set norelativenumber
augroup end

set encoding=utf8
set ffs=unix

set nobackup
set nowb
set noswapfile

set expandtab
set smarttab
set tabstop=4
set shiftwidth=4

set autoindent
set smartindent
set wrap

set background=dark

set hidden " allow hiding modified buffers

" automatically open files in hex mode
augroup binaryfile
    au!
    au BufReadPre   *.bin,*.class let &bin=1
    au BufReadPost  *.bin,*.class if &bin | %!xxd
    au BufReadPost  *.bin,*.class set filetype=xxd | endif
    au BufWritePre  *.bin,*.class if &bin | %!xxd -r
    au BufWritePre  *.bin,*.class endif
    au BufWritePost *.bin,*.class if &bin | %!xxd
    au BufWritePost *.bin,*.class set nomod | endif
augroup END

au FileType gitcommit au! BufEnter COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])

" return to last edit position when opening files
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" highlight trailing whitespace in red
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%$\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" unbind things
map <C-a> <Nop>
map <C-x> <Nop>
nmap Q <Nop>

" visual-mode pressing */# searches for current selection
vnoremap <silent> * :<C-u>call VisualSelection('', '')<cr>/<C-R>=@/<cr><cr>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<cr>/<C-R>=@/<cr><cr>

" move line (up|down) with Ctrl+[jk<up><down>]
"nmap <C-K> :m-2<cr>==
nmap <C-UP> :m-2<cr>==
"nmap <C-J> :m+<cr>==
nmap <C-DOWN> :m+<cr>==

" pretty-print JSON
map <leader>j :%!python -m json.tool<cr>

" copy / paste to system clipboard
vnoremap <C-c> "+yy
nnoremap <C-v> "+P

" accidental caps
command! W w
command! Q q
command! Wq wq
command! WQ wq
command! Qw wq
command! QW wq

" edit/source vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" save as sudo
cnoremap w!! execute 'silent! write !sudo tee % > /dev/null' <bar> edit!

" tell vim to re-detect filetype
cmap #! filetype detect<cr>

" move b/w windows
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-h> <C-w>h
map <C-l> <C-w>l

" create a new buffer (list all with :ls)
nmap <leader>t :enew<cr>

" close current buffer and move to previous
nmap <leader>q :bprevious<bar>bdelete #<cr>

" close all buffers
nmap <leader>Q :bufdo bd<cr>

" move b/w buffers
nmap <leader>l :bnext<cr>
nmap <leader>h :bprevious<cr>

" clang_complete
autocmd FileType c,cpp,objc ClangFormatAutoEnable
let g:clang_library_path='/usr/lib/x86_64-linux-gnu/libclang-6.0.so.1'
let g:clang_auto_select=0
let g:clang_close_preview=1
let g:clang_complete_macros=1

" vim-airline
let g:airline_theme='custom'
let g:airline#extensions#tabline#enabled = 1
let g:airline_symbols_ascii = 1

" CtrlP
" ---------------------------------------
" <c-f>/<c-b>   cycle b/w modes
" <c-d>         search filename only
" <c-r>         search regex
" <c-j>/<c-k>   navigate results list
" <c-t>         open in new tab
" <c-v>         open in vsplit
" <c-x>         open in xsplit
" <c-n>/<c-p>   cycle thru prompt history
" <c-y>         create new file & parent dirs
" <c-z>         mark/unmark file
" <c-o>         open marked files
" :<command>    execute <command> after opening (e.g. :25)
nmap <c-p> :CtrlP<cr>
let g:ctrlp_custom_ignore = {
    \   'dir':  '\v[\/](\.git|__pycache__|efs)$',
    \   'file': '\v\.(o|class|png|jpg|jpeg)$',
    \}
let g:ctrlp_max_files=0
let g:ctrlp_clear_cache_on_exit=0
let g:ctrlp_working_path_mode = 'r'

" black
let g:black_quiet=1
autocmd BufWritePre *.py execute ':Black'

if filereadable(expand('~/.vimrc.local'))
    source ~/.vimrc.local
endif

" autoformatting XML / HTML
function! Tidy(type)
    :silent execute "!tidy -q -mi -".a:type." -wrap %" | edit! | redraw!
endfunction
cnoremap <leader>xml call Tidy("xml")
cnoremap <leader>html call Tidy("html")

iabbrev @@ kevin@murp.us
